spring:
  profiles:
    active:
      - devabc
---
spring:
  profiles: devabc                   #开发环境
  application:
    name: microservice-config-dev
  server: 
    port: 7003
---
spring:
  profiles: testbcd                  #测试环境
  application:
    name: microservice-config-test

